theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "enp0s31f6"
format = "{ip} {speed_down} {speed_up}"
interval = 1
use_bits = false
hide_inactive = true

[[block]]
block = "net"
device = "wlp61s0"
format = "{ssid} {ip} {speed_down} {speed_up}"
hide_inactive = true
interval = 1
use_bits = false

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"

[[block]]
block = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUg}GB"
display_type = "memory"
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{alias} {percentage}"
info_type = "used"
interval = 20
warning = 80.0
alert = 90.0

[[block]]
block = "disk_space"
path = "/tmp"
alias = "/tmp"
format = "{alias} {percentage}"
info_type = "used"
interval = 20
warning = 80.0
alert = 90.0

# [[block]]
# block = "load"
# interval = 1
# format = "{1m} {5m} {15m}"

[[block]]
block = "sound"

# [[block]]
# block = "battery"
# driver = "sysfs"
# format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d-%m-%Y %R"
